import { User } from '../types';

class PaymentService {
  private razorpayKey: string;
  private razorpaySecret: string;

  constructor() {
    // In a real application, these would come from environment variables
    this.razorpayKey = (import.meta as any).env?.VITE_RAZORPAY_KEY_ID || 'PLACEHOLDER_RAZORPAY_KEY';
    this.razorpaySecret = (import.meta as any).env?.VITE_RAZORPAY_KEY_SECRET || 'PLACEHOLDER_RAZORPAY_SECRET';
  }

  /**
   * Create a Razorpay subscription for the user
   */
  async createRazorpaySubscription(userId: string): Promise<any> {
    try {
      // Create subscription payload
      const subscriptionData = {
        plan_id: (import.meta as any).env?.VITE_RAZORPAY_PLAN_ID || 'plan_Gr4RVS4t4k2q9e', // Default test plan
        customer_notify: 1, // Send notifications to customer
        quantity: 1,
        total_count: 12, // For recurring, set appropriately
        notes: {
          user_id: userId,
          purpose: 'GenSpark Premium Subscription'
        }
      };

      // In a real implementation, this would call the Razorpay API
      // For now, we'll simulate the response
      const response = {
        id: `sub_${Math.random().toString(36).substr(2, 9)}`,
        entity: 'subscription',
        plan_id: subscriptionData.plan_id,
        customer_id: `cust_${Math.random().toString(36).substr(2, 9)}`,
        status: 'active',
        current_start: Math.floor(Date.now() / 1000),
        current_end: Math.floor(Date.now() / 1000) + (30 * 24 * 60 * 60), // 30 days from now
        ended_at: null,
        quantity: 1,
        notes: subscriptionData.notes,
        created_at: Math.floor(Date.now() / 1000)
      };

      return response;
    } catch (error) {
      console.error('Error creating Razorpay subscription:', error);
      throw error;
    }
  }

  /**
   * Verify webhook signature from Razorpay
   */
  verifyWebhookSignature(payload: string, signature: string, secret: string): boolean {
    try {
      // In a real implementation, we would use crypto to verify the signature
      // This is a simplified version for demonstration
      // const crypto = require('crypto');
      // const expectedSignature = crypto
      //   .createHmac('sha256', secret)
      //   .update(payload)
      //   .digest('hex');
      // return expectedSignature === signature;

      // For demo purposes, we'll return true
      // In production, always verify the signature properly
      return true;
    } catch (error) {
      console.error('Error verifying webhook signature:', error);
      return false;
    }
  }

  /**
   * Create checkout options for Razorpay
   */
  createCheckoutOptions(userId: string, amount: number = 4900): any { // 4900 paise = ₹49
    const options = {
      key: this.razorpayKey,
      amount: amount.toString(), // Amount in paise (₹49 = 4900 paise)
      currency: 'INR',
      name: 'GenSpark',
      description: 'Premium Subscription',
      image: '/icons/logo.png', // Your logo
      order_id: '', // This would be generated by your backend
      handler: async (response: any) => {
        // This function is called when payment is successful
        console.log('Payment successful:', response);
        // Here you would typically call your backend to verify the payment
        // and update the user's subscription status
      },
      prefill: {
        name: '', // User's name
        email: '', // User's email
        contact: '' // User's contact
      },
      notes: {
        user_id: userId
      },
      theme: {
        color: '#4f46e5' // Tailwind indigo-600
      }
    };

    return options;
  }

  /**
   * Open Razorpay checkout
   */
  async openCheckout(userId: string, user: User) {
    // If Razorpay keys are not configured, show a message or use mock payment
    if (!this.razorpayKey || this.razorpayKey === '' || this.razorpayKey === 'PLACEHOLDER_RAZORPAY_KEY') {
      // For development/demo purposes, simulate payment success
      console.log('Razorpay not configured. Simulating payment for demo purposes...');

      // In a real app, you might redirect to a configuration page
      // For demo, we'll just return to simulate successful payment
      return new Promise<void>((resolve) => {
        setTimeout(() => {
          alert('Demo Mode: Payment would be processed with real Razorpay keys in production.');
          console.log('Demo: Simulated payment successful');
          resolve();
        }, 500);
      });
    }

    return new Promise<void>((resolve, reject) => {
      // Check if Razorpay script is already loaded
      if ((window as any).Razorpay) {
        this.initiateCheckout(userId, user).then(resolve).catch(reject);
        return;
      }

      // Load Razorpay script dynamically
      const script = document.createElement('script');
      script.src = 'https://checkout.razorpay.com/v1/checkout.js';
      script.async = true;

      script.onload = async () => {
        try {
          await this.initiateCheckout(userId, user);
          resolve();
        } catch (error) {
          reject(error);
        }
      };

      script.onerror = () => {
        reject(new Error('Failed to load payment gateway. Please check your connection.'));
      };

      document.body.appendChild(script);
    });
  }

  private async initiateCheckout(userId: string, user: User) {
    const options = this.createCheckoutOptions(userId);

    // Set user details
    options.prefill.name = user.name || '';
    options.prefill.email = user.email || '';

    // In a real implementation, you would create an order on your backend first
    // and get the order_id to set in options.order_id
    // For now, we'll skip this step in the frontend-only demo

    const rzp = new (window as any).Razorpay(options);
    rzp.open();
  }
}

export const paymentService = new PaymentService();